### ISSUE TITLE
DEFINES_MODULE flag is disabled

### ISSUE THREAD

**Issue by szotp** [sbooth/AudioXCFrameworks#32]
Hi, thanks for this repo. One thing I noticed is that those frameworks don't define modules so they can't be used from swift, or imported in modular way (can't do `@import opus;`) in Objective-C. Not sure it was intended or not. I made a fork to change this for libraries that I needed, and it seems to be working.

I had to write a custom modulemap because opus.h name is already taken, but it is not an umbrella framework.

Changes I needed for my project: https://github.com/beekpr/ios-AudioXCFrameworks/commit/af7e24e6f10e3bf2b5665404cfbf1bea167a0060

**Comment by sbooth** [comment]
This was intentional only because I was trying to keep everything standard across the frameworks, mostly since modules for C++ frameworks aren't usable from Swift or ObjC and I created these frameworks specifically for SFBAudioEngine. But perhaps I didn't sufficiently consider other use cases. I don't think there is a technical reason that a C++ framework can't create a module so it probably makes sense to do so.  I'll have to experiment because C++20 has native modules and I don't know how that relates to non-C++20 code and older versions of clang. But in any case it should be simple for the C-only frameworks.

**Comment by sbooth** [comment]
The C libraries now define modules as of 3316b5d3728399c77d8736da9b3036a11e7161f9
